// Copyright 2026 Sunbeam Studios
// SPDX-License-Identifier: MIT OR Apache-2.0

//! Manifest XML serialization.
//!
//! This module writes a [`Manifest`] back to an XML string.

use crate::model::*;
use quick_xml::events::{BytesEnd, BytesStart, BytesText, Event};
use quick_xml::writer::Writer;
use std::collections::HashSet;
use std::io::Write;

/// Serialize a manifest to an XML string.
///
/// # Errors
///
/// Returns an error if XML serialization fails.
pub fn manifest_to_xml(manifest: &Manifest) -> Result<String, crate::Error> {
    let mut buf = Vec::new();
    {
        let mut writer = Writer::new_with_indent(&mut buf, b' ', 2);
        writer.write_event(Event::Decl(quick_xml::events::BytesDecl::new(
            "1.0",
            Some("UTF-8"),
            None,
        )))?;
        writer.write_event(Event::Comment(BytesText::new(
            " DO NOT EDIT: generated by repo-rs ",
        )))?;

        let root = BytesStart::new("manifest");
        writer.write_event(Event::Start(root.clone()))?;

        // Notice
        if let Some(notice) = &manifest.notice {
            writer.write_event(Event::Start(BytesStart::new("notice")))?;
            writer.write_event(Event::Text(BytesText::new(notice)))?;
            writer.write_event(Event::End(BytesEnd::new("notice")))?;
        }

        // Remotes
        for remote in manifest.remotes.values() {
            write_remote(&mut writer, remote)?;
        }

        // Default
        if let Some(default) = &manifest.default {
            write_default(&mut writer, default)?;
        }

        // Manifest server
        if let Some(url) = &manifest.manifest_server {
            let mut elem = BytesStart::new("manifest-server");
            elem.push_attribute(("url", url.as_str()));
            writer.write_event(Event::Empty(elem))?;
        }

        // Contactinfo
        if let Some(contact) = &manifest.contactinfo {
            let mut elem = BytesStart::new("contactinfo");
            elem.push_attribute(("bugurl", contact.bugurl.as_str()));
            writer.write_event(Event::Empty(elem))?;
        }

        // Superproject
        if let Some(superproject) = &manifest.superproject {
            write_superproject(&mut writer, superproject)?;
        }

        // Repo hooks
        if let Some(hooks) = &manifest.repo_hooks {
            let mut elem = BytesStart::new("repo-hooks");
            elem.push_attribute(("in-project", hooks.in_project.as_str()));
            elem.push_attribute(("enabled-list", hooks.enabled_list.as_str()));
            writer.write_event(Event::Empty(elem))?;
        }

        // Submanifests
        for submanifest in manifest.submanifests.values() {
            write_submanifest(&mut writer, submanifest)?;
        }

        // Includes
        for include in &manifest.includes {
            write_include(&mut writer, include)?;
        }

        // Projects
        for project in &manifest.projects {
            write_project(&mut writer, project)?;
        }

        // Extend-projects
        for ext in &manifest.extend_projects {
            write_extend_project(&mut writer, ext)?;
        }

        // Remove-projects
        for rem in &manifest.remove_projects {
            write_remove_project(&mut writer, rem)?;
        }

        writer.write_event(Event::End(BytesEnd::new("manifest")))?;
    }

    Ok(String::from_utf8(buf).map_err(|e| crate::Error::Encoding(e.to_string()))?)
}

fn write_remote<W: Write>(
    writer: &mut Writer<W>,
    remote: &Remote,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("remote");
    elem.push_attribute(("name", remote.name.as_str()));
    elem.push_attribute(("fetch", remote.fetch.as_str()));
    if let Some(alias) = &remote.alias {
        elem.push_attribute(("alias", alias.as_str()));
    }
    if let Some(pushurl) = &remote.pushurl {
        elem.push_attribute(("pushurl", pushurl.as_str()));
    }
    if let Some(review) = &remote.review {
        elem.push_attribute(("review", review.as_str()));
    }
    if let Some(revision) = &remote.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }

    if remote.annotations.is_empty() {
        writer.write_event(Event::Empty(elem))?;
    } else {
        writer.write_event(Event::Start(elem))?;
        for ann in &remote.annotations {
            write_annotation(writer, ann)?;
        }
        writer.write_event(Event::End(BytesEnd::new("remote")))?;
    }
    Ok(())
}

fn write_default<W: Write>(
    writer: &mut Writer<W>,
    default: &Default,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("default");
    if let Some(remote) = &default.remote {
        elem.push_attribute(("remote", remote.as_str()));
    }
    if let Some(revision) = &default.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }
    if let Some(dest_branch) = &default.dest_branch {
        elem.push_attribute(("dest-branch", dest_branch.as_str()));
    }
    if let Some(upstream) = &default.upstream {
        elem.push_attribute(("upstream", upstream.as_str()));
    }
    if let Some(sync_j) = default.sync_j {
        elem.push_attribute(("sync-j", sync_j.to_string().as_str()));
    }
    if let Some(sync_j_max) = default.sync_j_max {
        elem.push_attribute(("sync-j-max", sync_j_max.to_string().as_str()));
    }
    if let Some(sync_c) = default.sync_c {
        elem.push_attribute(("sync-c", if sync_c { "true" } else { "false" }));
    }
    if let Some(sync_s) = default.sync_s {
        elem.push_attribute(("sync-s", if sync_s { "true" } else { "false" }));
    }
    if let Some(sync_tags) = default.sync_tags {
        elem.push_attribute(("sync-tags", if sync_tags { "true" } else { "false" }));
    }
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_project<W: Write>(
    writer: &mut Writer<W>,
    project: &Project,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("project");
    elem.push_attribute(("name", project.name.as_str()));
    if let Some(path) = &project.path {
        elem.push_attribute(("path", path.as_str()));
    }
    if let Some(remote) = &project.remote {
        elem.push_attribute(("remote", remote.as_str()));
    }
    if let Some(revision) = &project.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }
    if let Some(dest_branch) = &project.dest_branch {
        elem.push_attribute(("dest-branch", dest_branch.as_str()));
    }
    if let Some(upstream) = &project.upstream {
        elem.push_attribute(("upstream", upstream.as_str()));
    }
    if !project.groups.is_empty() {
        elem.push_attribute(("groups", groups_to_string(&project.groups).as_str()));
    }
    if let Some(sync_c) = project.sync_c {
        elem.push_attribute(("sync-c", if sync_c { "true" } else { "false" }));
    }
    if let Some(sync_s) = project.sync_s {
        elem.push_attribute(("sync-s", if sync_s { "true" } else { "false" }));
    }
    if let Some(sync_tags) = project.sync_tags {
        elem.push_attribute(("sync-tags", if sync_tags { "true" } else { "false" }));
    }
    if let Some(clone_depth) = project.clone_depth {
        elem.push_attribute(("clone-depth", clone_depth.to_string().as_str()));
    }
    if let Some(force_path) = project.force_path {
        elem.push_attribute(("force-path", if force_path { "true" } else { "false" }));
    }
    if let Some(sync_strategy) = &project.sync_strategy {
        elem.push_attribute(("sync-strategy", sync_strategy.as_str()));
    }
    if let Some(rebase) = project.rebase {
        elem.push_attribute(("rebase", if rebase { "true" } else { "false" }));
    }

    let has_children = !project.annotations.is_empty()
        || !project.copyfiles.is_empty()
        || !project.linkfiles.is_empty()
        || !project.subprojects.is_empty();

    if has_children {
        writer.write_event(Event::Start(elem))?;
        for ann in &project.annotations {
            write_annotation(writer, ann)?;
        }
        for cf in &project.copyfiles {
            write_copyfile(writer, cf)?;
        }
        for lf in &project.linkfiles {
            write_linkfile(writer, lf)?;
        }
        for sub in &project.subprojects {
            write_project(writer, sub)?;
        }
        writer.write_event(Event::End(BytesEnd::new("project")))?;
    } else {
        writer.write_event(Event::Empty(elem))?;
    }
    Ok(())
}

fn write_extend_project<W: Write>(
    writer: &mut Writer<W>,
    ext: &ExtendProject,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("extend-project");
    elem.push_attribute(("name", ext.name.as_str()));
    if let Some(path) = &ext.path {
        elem.push_attribute(("path", path.as_str()));
    }
    if let Some(dest_path) = &ext.dest_path {
        elem.push_attribute(("dest-path", dest_path.as_str()));
    }
    if !ext.groups.is_empty() {
        elem.push_attribute(("groups", groups_to_string(&ext.groups).as_str()));
    }
    if let Some(revision) = &ext.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }
    if let Some(remote) = &ext.remote {
        elem.push_attribute(("remote", remote.as_str()));
    }
    if let Some(dest_branch) = &ext.dest_branch {
        elem.push_attribute(("dest-branch", dest_branch.as_str()));
    }
    if let Some(upstream) = &ext.upstream {
        elem.push_attribute(("upstream", upstream.as_str()));
    }
    if let Some(base_rev) = &ext.base_rev {
        elem.push_attribute(("base-rev", base_rev.as_str()));
    }

    let has_children = !ext.annotations.is_empty()
        || !ext.copyfiles.is_empty()
        || !ext.linkfiles.is_empty();

    if has_children {
        writer.write_event(Event::Start(elem))?;
        for ann in &ext.annotations {
            write_annotation(writer, ann)?;
        }
        for cf in &ext.copyfiles {
            write_copyfile(writer, cf)?;
        }
        for lf in &ext.linkfiles {
            write_linkfile(writer, lf)?;
        }
        writer.write_event(Event::End(BytesEnd::new("extend-project")))?;
    } else {
        writer.write_event(Event::Empty(elem))?;
    }
    Ok(())
}

fn write_remove_project<W: Write>(
    writer: &mut Writer<W>,
    rem: &RemoveProject,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("remove-project");
    if let Some(name) = &rem.name {
        elem.push_attribute(("name", name.as_str()));
    }
    if let Some(path) = &rem.path {
        elem.push_attribute(("path", path.as_str()));
    }
    if rem.optional {
        elem.push_attribute(("optional", "true"));
    }
    if let Some(base_rev) = &rem.base_rev {
        elem.push_attribute(("base-rev", base_rev.as_str()));
    }
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_submanifest<W: Write>(
    writer: &mut Writer<W>,
    sub: &Submanifest,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("submanifest");
    elem.push_attribute(("name", sub.name.as_str()));
    if let Some(remote) = &sub.remote {
        elem.push_attribute(("remote", remote.as_str()));
    }
    if let Some(project) = &sub.project {
        elem.push_attribute(("project", project.as_str()));
    }
    if let Some(manifest_name) = &sub.manifest_name {
        elem.push_attribute(("manifest-name", manifest_name.as_str()));
    }
    if let Some(revision) = &sub.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }
    if let Some(path) = &sub.path {
        elem.push_attribute(("path", path.as_str()));
    }
    if !sub.groups.is_empty() {
        elem.push_attribute(("groups", groups_to_string(&sub.groups).as_str()));
    }
    if !sub.default_groups.is_empty() {
        elem.push_attribute((
            "default-groups",
            groups_to_string(&sub.default_groups).as_str(),
        ));
    }
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_include<W: Write>(
    writer: &mut Writer<W>,
    include: &Include,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("include");
    elem.push_attribute(("name", include.name.as_str()));
    if !include.groups.is_empty() {
        elem.push_attribute(("groups", groups_to_string(&include.groups).as_str()));
    }
    if let Some(revision) = &include.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_annotation<W: Write>(
    writer: &mut Writer<W>,
    ann: &Annotation,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("annotation");
    elem.push_attribute(("name", ann.name.as_str()));
    elem.push_attribute(("value", ann.value.as_str()));
    if !ann.keep {
        elem.push_attribute(("keep", "false"));
    }
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_copyfile<W: Write>(
    writer: &mut Writer<W>,
    cf: &CopyFile,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("copyfile");
    elem.push_attribute(("src", cf.src.as_str()));
    elem.push_attribute(("dest", cf.dest.as_str()));
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_linkfile<W: Write>(
    writer: &mut Writer<W>,
    lf: &LinkFile,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("linkfile");
    elem.push_attribute(("src", lf.src.as_str()));
    elem.push_attribute(("dest", lf.dest.as_str()));
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn write_superproject<W: Write>(
    writer: &mut Writer<W>,
    sp: &Superproject,
) -> Result<(), crate::Error> {
    let mut elem = BytesStart::new("superproject");
    elem.push_attribute(("name", sp.name.as_str()));
    if let Some(remote) = &sp.remote {
        elem.push_attribute(("remote", remote.as_str()));
    }
    if let Some(revision) = &sp.revision {
        elem.push_attribute(("revision", revision.as_str()));
    }
    writer.write_event(Event::Empty(elem))?;
    Ok(())
}

fn groups_to_string(groups: &HashSet<String>) -> String {
    let mut sorted: Vec<&str> = groups.iter().map(|s| s.as_str()).collect();
    sorted.sort_unstable();
    sorted.join(",")
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser::parse_manifest;
    use std::collections::HashSet;

    #[test]
    fn serialize_minimal_manifest() {
        let manifest = Manifest {
            remotes: {
                let mut m = indexmap::IndexMap::new();
                m.insert(
                    "origin".to_string(),
                    Remote {
                        name: "origin".to_string(),
                        alias: None,
                        fetch: "https://example.com".to_string(),
                        pushurl: None,
                        review: None,
                        revision: Some("main".to_string()),
                        annotations: Vec::new(),
                    },
                );
                m
            },
            default: Some(Default {
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
                ..Default::default()
            }),
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
                ..Project::default_test()
            }],
            ..Manifest::default()
        };

        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains(r#"<remote name="origin" fetch="https://example.com" revision="main"/>"#));
        assert!(xml.contains(r#"<default remote="origin" revision="main"/>"#));
        assert!(xml.contains(r#"<project name="foo" path="foo" remote="origin" revision="main"/>"#));
    }

    #[test]
    fn serialize_manifest_with_notice() {
        let manifest = Manifest {
            notice: Some("Hello\nWorld".to_string()),
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains("<notice>"));
        assert!(xml.contains("Hello"));
        assert!(xml.contains("World"));
    }

    #[test]
    fn serialize_manifest_with_groups() {
        let manifest = Manifest {
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                groups: ["group1".to_string(), "group2".to_string()]
                    .into_iter()
                    .collect(),
                ..Project::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains(r#"groups="group1,group2""#) || xml.contains(r#"groups="group2,group1""#));
    }

    #[test]
    fn serialize_manifest_with_children() {
        let manifest = Manifest {
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                annotations: vec![Annotation {
                    name: "ann".to_string(),
                    value: "val".to_string(),
                    keep: true,
                }],
                copyfiles: vec![CopyFile {
                    src: "a".to_string(),
                    dest: "b".to_string(),
                }],
                linkfiles: vec![LinkFile {
                    src: "c".to_string(),
                    dest: "d".to_string(),
                }],
                subprojects: vec![Project {
                    name: "sub".to_string(),
                    path: Some("sub".to_string()),
                    ..Project::default_test()
                }],
                ..Project::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains("<annotation"));
        assert!(xml.contains("<copyfile"));
        assert!(xml.contains("<linkfile"));
        assert!(xml.contains(r#"<project name="sub""#));
    }

    #[test]
    fn serialize_manifest_with_all_elements() {
        let manifest = Manifest {
            notice: Some("Notice".to_string()),
            remotes: {
                let mut m = indexmap::IndexMap::new();
                m.insert(
                    "origin".to_string(),
                    Remote {
                        name: "origin".to_string(),
                        alias: Some("o".to_string()),
                        fetch: "https://example.com".to_string(),
                        pushurl: Some("https://push.example.com".to_string()),
                        review: Some("https://review.example.com".to_string()),
                        revision: Some("main".to_string()),
                        annotations: Vec::new(),
                    },
                );
                m
            },
            default: Some(Default {
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
                dest_branch: Some("main".to_string()),
                upstream: Some("main".to_string()),
                sync_j: Some(4),
                sync_j_max: Some(8),
                sync_c: Some(true),
                sync_s: Some(false),
                sync_tags: Some(true),
            }),
            manifest_server: Some("https://manifest.example.com".to_string()),
            contactinfo: Some(ContactInfo {
                bugurl: "https://bugs.example.com".to_string(),
            }),
            superproject: Some(Superproject {
                name: "super".to_string(),
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
            }),
            repo_hooks: Some(RepoHooks {
                in_project: "hooks".to_string(),
                enabled_list: "list.txt".to_string(),
            }),
            submanifests: {
                let mut m = indexmap::IndexMap::new();
                m.insert(
                    "sub".to_string(),
                    Submanifest {
                        name: "sub".to_string(),
                        remote: Some("origin".to_string()),
                        project: Some("proj".to_string()),
                        manifest_name: Some("default.xml".to_string()),
                        revision: Some("main".to_string()),
                        path: Some("sub".to_string()),
                        groups: ["g1".to_string()].into_iter().collect(),
                        default_groups: ["dg1".to_string()].into_iter().collect(),
                    },
                );
                m
            },
            includes: vec![Include {
                name: "other.xml".to_string(),
                groups: ["ig1".to_string()].into_iter().collect(),
                revision: Some("main".to_string()),
            }],
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
                dest_branch: Some("main".to_string()),
                upstream: Some("main".to_string()),
                groups: HashSet::new(),
                sync_c: Some(true),
                sync_s: Some(false),
                sync_tags: Some(true),
                clone_depth: Some(1),
                force_path: Some(true),
                sync_strategy: Some("auto".to_string()),
                rebase: None,
                annotations: Vec::new(),
                copyfiles: Vec::new(),
                linkfiles: Vec::new(),
                subprojects: Vec::new(),
            }],
            extend_projects: vec![ExtendProject {
                name: "foo".to_string(),
                path: Some("bar".to_string()),
                dest_path: Some("baz".to_string()),
                groups: ["eg1".to_string()].into_iter().collect(),
                revision: Some("dev".to_string()),
                remote: Some("origin".to_string()),
                dest_branch: Some("dev".to_string()),
                upstream: Some("dev".to_string()),
                base_rev: Some("abc".to_string()),
                annotations: vec![Annotation {
                    name: "eann".to_string(),
                    value: "eval".to_string(),
                    keep: false,
                }],
                copyfiles: vec![CopyFile {
                    src: "e".to_string(),
                    dest: "f".to_string(),
                }],
                linkfiles: vec![LinkFile {
                    src: "g".to_string(),
                    dest: "h".to_string(),
                }],
            }],
            remove_projects: vec![RemoveProject {
                name: Some("old".to_string()),
                path: Some("oldpath".to_string()),
                optional: true,
                base_rev: Some("def".to_string()),
            }],
        };

        let xml = manifest_to_xml(&manifest).unwrap();

        // Verify all major elements are present
        assert!(xml.contains("<notice>"));
        assert!(xml.contains("<remote"));
        assert!(xml.contains("<default"));
        assert!(xml.contains("<manifest-server"));
        assert!(xml.contains("<contactinfo"));
        assert!(xml.contains("<superproject"));
        assert!(xml.contains("<repo-hooks"));
        assert!(xml.contains("<submanifest"));
        assert!(xml.contains("<include"));
        assert!(xml.contains("<project"));
        assert!(xml.contains("<extend-project"));
        assert!(xml.contains("<remove-project"));
        assert!(xml.contains("<annotation"));
        assert!(xml.contains("<copyfile"));
        assert!(xml.contains("<linkfile"));

        // Verify some attributes
        assert!(xml.contains(r#"alias="o""#));
        assert!(xml.contains(r#"pushurl="https://push.example.com""#));
        assert!(xml.contains(r#"review="https://review.example.com""#));
        assert!(xml.contains(r#"dest-branch="main""#));
        assert!(xml.contains(r#"upstream="main""#));
        assert!(xml.contains(r#"sync-j="4""#));
        assert!(xml.contains(r#"sync-j-max="8""#));
        assert!(xml.contains(r#"sync-c="true""#));
        assert!(xml.contains(r#"sync-s="false""#));
        assert!(xml.contains(r#"sync-tags="true""#));
        assert!(xml.contains(r#"clone-depth="1""#));
        assert!(xml.contains(r#"force-path="true""#));
        assert!(xml.contains(r#"sync-strategy="auto""#));
        assert!(xml.contains(r#"optional="true""#));
        assert!(xml.contains(r#"base-rev="abc""#));
        assert!(xml.contains(r#"keep="false""#));
    }

    #[test]
    fn serialize_and_parse_roundtrip() {
        let original = Manifest {
            notice: Some("Hello World".to_string()),
            remotes: {
                let mut m = indexmap::IndexMap::new();
                m.insert(
                    "origin".to_string(),
                    Remote {
                        name: "origin".to_string(),
                        alias: None,
                        fetch: "https://example.com".to_string(),
                        pushurl: None,
                        review: None,
                        revision: Some("main".to_string()),
                        annotations: Vec::new(),
                    },
                );
                m
            },
            default: Some(Default {
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
                ..Default::default()
            }),
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                remote: Some("origin".to_string()),
                revision: Some("main".to_string()),
                groups: ["g1".to_string()].into_iter().collect(),
                ..Project::default_test()
            }],
            ..Manifest::default()
        };

        let xml = manifest_to_xml(&original).unwrap();
        let parsed = parse_manifest(&xml).unwrap();

        assert_eq!(parsed.notice, original.notice);
        assert_eq!(parsed.remotes.len(), original.remotes.len());
        assert_eq!(parsed.projects.len(), original.projects.len());
        assert_eq!(parsed.projects[0].name, original.projects[0].name);
        assert_eq!(parsed.projects[0].path, original.projects[0].path);
    }

    #[test]
    fn serialize_empty_manifest() {
        let manifest = Manifest::default();
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains("<manifest>"));
        assert!(xml.contains("</manifest>"));
    }

    #[test]
    fn serialize_remote_with_annotations() {
        let manifest = Manifest {
            remotes: {
                let mut m = indexmap::IndexMap::new();
                m.insert(
                    "origin".to_string(),
                    Remote {
                        name: "origin".to_string(),
                        alias: None,
                        fetch: "https://example.com".to_string(),
                        pushurl: None,
                        review: None,
                        revision: None,
                        annotations: vec![Annotation {
                            name: "ann".to_string(),
                            value: "val".to_string(),
                            keep: true,
                        }],
                    },
                );
                m
            },
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains("<remote"));
        assert!(xml.contains("<annotation"));
        assert!(xml.contains("</remote>"));
    }

    #[test]
    fn serialize_extend_project_empty() {
        let manifest = Manifest {
            extend_projects: vec![ExtendProject {
                name: "foo".to_string(),
                ..ExtendProject::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains(r#"<extend-project name="foo"/>"#));
    }

    #[test]
    fn serialize_extend_project_with_children() {
        let manifest = Manifest {
            extend_projects: vec![ExtendProject {
                name: "foo".to_string(),
                annotations: vec![Annotation {
                    name: "ann".to_string(),
                    value: "val".to_string(),
                    keep: true,
                }],
                copyfiles: vec![CopyFile {
                    src: "a".to_string(),
                    dest: "b".to_string(),
                }],
                linkfiles: vec![LinkFile {
                    src: "c".to_string(),
                    dest: "d".to_string(),
                }],
                ..ExtendProject::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains("<extend-project"));
        assert!(xml.contains("<annotation"));
        assert!(xml.contains("<copyfile"));
        assert!(xml.contains("<linkfile"));
        assert!(xml.contains("</extend-project>"));
    }

    #[test]
    fn serialize_project_with_rebase_false() {
        let manifest = Manifest {
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                rebase: Some(false),
                ..Project::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains(r#"rebase="false""#));
    }

    #[test]
    fn serialize_project_with_rebase_true() {
        let manifest = Manifest {
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                rebase: Some(true),
                ..Project::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(xml.contains(r#"rebase="true""#));
    }

    #[test]
    fn serialize_project_omits_rebase_when_none() {
        let manifest = Manifest {
            projects: vec![Project {
                name: "foo".to_string(),
                path: Some("foo".to_string()),
                rebase: None,
                ..Project::default_test()
            }],
            ..Manifest::default()
        };
        let xml = manifest_to_xml(&manifest).unwrap();
        assert!(!xml.contains("rebase"));
    }
}
