[package]
name = "repo-rs-manifest"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Manifest parsing and management for repo-rs"
repository.workspace = true
keywords = ["repo", "git", "manifest"]
categories = ["development-tools"]

[dependencies]
quick-xml = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
url = { workspace = true }
tracing = { workspace = true }
camino = { workspace = true }
indexmap = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
